# Generated by Django 5.2 on 2025-04-21 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhitelistApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_name', models.CharField(help_text='Discord Name & Tag (e.g., JohnDoe#1234)', max_length=100)),
                ('steam_name', models.CharField(help_text='Steam Name', max_length=100)),
                ('steam_hex_id', models.CharField(help_text='Steam Hex ID', max_length=100)),
                ('age', models.PositiveIntegerField(help_text='Your age')),
                ('fivem_experience', models.TextField(help_text='How long have you been playing on FiveM?')),
                ('character_name', models.CharField(help_text='Character Name (First & Last)', max_length=100)),
                ('character_age', models.PositiveIntegerField(help_text='Character Age')),
                ('rule_breaking_response', models.TextField(help_text='What would you do if you saw someone breaking the rules?')),
                ('rules_acknowledged', models.BooleanField(default=False, help_text='Do you agree to follow all rules and respect staff decisions?')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
