# Generated by Django 4.1.13 on 2025-04-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitelist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whitelistapplication',
            name='age',
        ),
        migrations.RemoveField(
            model_name='whitelistapplication',
            name='age_verified',
        ),
        migrations.AddField(
            model_name='whitelistapplication',
            name='discord_name',
            field=models.CharField(default=1, help_text='Your Discord username', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whitelistapplication',
            name='your_age',
            field=models.PositiveIntegerField(default=1, help_text='Your real age'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whitelistapplication',
            name='your_gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default=1, help_text='Your gender', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whitelistapplication',
            name='your_name',
            field=models.CharField(default=1, help_text='Your real name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='whitelistapplication',
            name='character_name',
            field=models.CharField(help_text="Your character's name", max_length=100),
        ),
        migrations.AlterField(
            model_name='whitelistapplication',
            name='rules_acknowledged',
            field=models.BooleanField(default=False, help_text='I have read and understood the server rules'),
        ),
    ]
