# Generated by Django 5.2 on 2025-04-21 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whitelist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whitelistapplication',
            name='fail_rp_explanation',
        ),
        migrations.RemoveField(
            model_name='whitelistapplication',
            name='fear_rp_explanation',
        ),
        migrations.RemoveField(
            model_name='whitelistapplication',
            name='how_found',
        ),
        migrations.RemoveField(
            model_name='whitelistapplication',
            name='robbery_response',
        ),
    ]
