# Generated by Django 5.2 on 2025-04-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitelist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whitelistapplication',
            name='character_gender',
        ),
        migrations.RemoveField(
            model_name='whitelistapplication',
            name='rules_acknowledged',
        ),
        migrations.RemoveField(
            model_name='whitelistapplication',
            name='your_gender',
        ),
        migrations.RemoveField(
            model_name='whitelistapplication',
            name='your_name',
        ),
        migrations.AddField(
            model_name='whitelistapplication',
            name='character_backstory',
            field=models.TextField(default=1, help_text="Your character's backstory (minimum 5 sentences)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whitelistapplication',
            name='fail_rp_explanation',
            field=models.TextField(default=1, help_text='What is FailRP? Give an example.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whitelistapplication',
            name='fear_rp_explanation',
            field=models.TextField(default=1, help_text='What is FearRP?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whitelistapplication',
            name='fivem_experience',
            field=models.TextField(default=1, help_text='How long have you been playing on FiveM?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whitelistapplication',
            name='how_found_server',
            field=models.TextField(default=1, help_text='How did you find our server?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whitelistapplication',
            name='robbery_response',
            field=models.TextField(default=1, help_text="You're being robbed at gunpoint. What do you do, and what should your character value?"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whitelistapplication',
            name='rule_breaking_response',
            field=models.TextField(default=1, help_text='What would you do if you saw someone breaking the rules?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whitelistapplication',
            name='rules_agreement',
            field=models.BooleanField(default=False, help_text='Do you agree to follow all rules and respect staff decisions?'),
        ),
        migrations.AddField(
            model_name='whitelistapplication',
            name='steam_hex_id',
            field=models.CharField(default=1, help_text='Your Steam Hex ID', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whitelistapplication',
            name='steam_name',
            field=models.CharField(default=1, help_text='Your Steam username', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='whitelistapplication',
            name='character_name',
            field=models.CharField(help_text="Your character's first and last name", max_length=100),
        ),
        migrations.AlterField(
            model_name='whitelistapplication',
            name='discord_name',
            field=models.CharField(default=1, help_text='Your Discord username and tag (e.g., JohnDoe#1234)', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='whitelistapplication',
            name='your_age',
            field=models.PositiveIntegerField(default=1, help_text='Your real age'),
            preserve_default=False,
        ),
    ]
