# Generated by Django 5.2 on 2025-04-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitelist', '0002_remove_whitelistapplication_character_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whitelistapplication',
            old_name='how_found_server',
            new_name='how_found',
        ),
        migrations.RenameField(
            model_name='whitelistapplication',
            old_name='rules_agreement',
            new_name='rules_acknowledged',
        ),
        migrations.RenameField(
            model_name='whitelistapplication',
            old_name='steam_hex_id',
            new_name='steam_hex',
        ),
        migrations.AlterField(
            model_name='whitelistapplication',
            name='steam_name',
            field=models.CharField(help_text='Your Steam name', max_length=100),
        ),
    ]
