# Generated by Django 4.1.13 on 2025-04-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitelist', '0002_remove_whitelistapplication_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitelistapplication',
            name='discord_name',
            field=models.CharField(blank=True, help_text='Your Discord username', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='whitelistapplication',
            name='your_age',
            field=models.PositiveIntegerField(blank=True, help_text='Your real age', null=True),
        ),
        migrations.AlterField(
            model_name='whitelistapplication',
            name='your_gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text='Your gender', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='whitelistapplication',
            name='your_name',
            field=models.CharField(blank=True, help_text='Your real name', max_length=100, null=True),
        ),
    ]
