# Generated by Django 5.2 on 2025-04-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitelist', '0003_rename_how_found_server_whitelistapplication_how_found_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whitelistapplication',
            name='character_backstory',
        ),
        migrations.RemoveField(
            model_name='whitelistapplication',
            name='fail_rp_explanation',
        ),
        migrations.RemoveField(
            model_name='whitelistapplication',
            name='fear_rp_explanation',
        ),
        migrations.RemoveField(
            model_name='whitelistapplication',
            name='fivem_experience',
        ),
        migrations.RemoveField(
            model_name='whitelistapplication',
            name='how_found',
        ),
        migrations.RemoveField(
            model_name='whitelistapplication',
            name='robbery_response',
        ),
        migrations.RemoveField(
            model_name='whitelistapplication',
            name='rule_breaking_response',
        ),
        migrations.RemoveField(
            model_name='whitelistapplication',
            name='steam_hex',
        ),
        migrations.RemoveField(
            model_name='whitelistapplication',
            name='steam_name',
        ),
        migrations.AddField(
            model_name='whitelistapplication',
            name='character_gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default=1, help_text="Your character's gender", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whitelistapplication',
            name='your_gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text='Your gender', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='whitelistapplication',
            name='your_name',
            field=models.CharField(blank=True, help_text='Your real name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='whitelistapplication',
            name='character_name',
            field=models.CharField(help_text="Your character's name", max_length=100),
        ),
        migrations.AlterField(
            model_name='whitelistapplication',
            name='discord_name',
            field=models.CharField(blank=True, help_text='Your Discord username', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='whitelistapplication',
            name='rules_acknowledged',
            field=models.BooleanField(default=False, help_text='I have read and understood the server rules'),
        ),
        migrations.AlterField(
            model_name='whitelistapplication',
            name='your_age',
            field=models.PositiveIntegerField(blank=True, help_text='Your real age', null=True),
        ),
    ]
