# Generated by Django 5.2 on 2025-04-20 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whitelist', '0005_remove_whitelistapplication_character_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whitelistapplication',
            name='character_backstory',
        ),
    ]
