# Generated by Django 5.2 on 2025-04-06 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('SASP', 'San Andreas State Police'), ('EMS', 'Emergency Medical Services'), ('MECHANIC', 'Mechanic')], max_length=10)),
                ('character_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(help_text='In-game character date of birth')),
                ('previous_experience', models.TextField(blank=True, help_text='Describe any relevant previous experience.')),
                ('reason', models.TextField(help_text='Why are you applying for this position?')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Form Review'), ('INTERVIEW_PENDING', 'Pending Interview'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected (Form Stage)'), ('REJECTED_INTERVIEW', 'Rejected (Interview Stage)')], default='PENDING', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('form_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('form_feedback', models.TextField(blank=True, help_text='Feedback provided during form review.', null=True)),
                ('interview_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('interview_feedback', models.TextField(blank=True, help_text='Feedback provided during/after interview.', null=True)),
                ('sasp_scenario_response', models.TextField(blank=True, help_text='Describe how you would handle a specific scenario (e.g., a high-speed pursuit ending in a crash).', null=True)),
                ('sasp_leadership_experience', models.TextField(blank=True, help_text='Describe any relevant leadership experience (Optional).', null=True)),
                ('ems_medical_certification', models.CharField(blank=True, help_text='Do you hold any relevant medical certifications? (e.g., EMT, Paramedic) (Optional)', max_length=255, null=True)),
                ('ems_pressure_handling', models.TextField(blank=True, help_text='Describe how you handle high-pressure situations.', null=True)),
                ('mechanic_skills', models.TextField(blank=True, help_text='List your relevant mechanical skills and experience (e.g., engine repair, tuning, bodywork).', null=True)),
                ('mechanic_tool_knowledge', models.BooleanField(blank=True, help_text='Do you own or have extensive knowledge of specialized mechanic tools? (Optional)', null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('form_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_job_forms', to=settings.AUTH_USER_MODEL)),
                ('interview_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviewed_job_applicants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
