# Generated by Django 4.1.13 on 2025-04-05 17:01

import datetime # Import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='character_name',
            field=models.CharField(default='Unknown', max_length=100), # Changed default
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(1900, 1, 1), help_text='In-game character date of birth'), # Changed default
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='previous_experience',
            field=models.TextField(blank=True, help_text='Describe any relevant previous experience.'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='reason',
            field=models.TextField(help_text='Why are you applying for this position?'),
        ),
    ]
