# Generated by Django 5.2 on 2025-04-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Form Review'), ('INTERVIEW_PENDING', 'Pending Interview'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected (Form Stage)'), ('REJECTED_INTERVIEW', 'Rejected (Interview Stage)'), ('FIRED', 'Fired')], default='PENDING', max_length=20),
        ),
    ]
