# Generated by Django 4.1.13 on 2025-04-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobapplication_character_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='ems_medical_certification',
            field=models.CharField(blank=True, help_text='Do you hold any relevant medical certifications? (e.g., EMT, Paramedic) (Optional)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='ems_pressure_handling',
            field=models.TextField(blank=True, help_text='Describe how you handle high-pressure situations.', null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='mechanic_skills',
            field=models.TextField(blank=True, help_text='List your relevant mechanical skills and experience (e.g., engine repair, tuning, bodywork).', null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='mechanic_tool_knowledge',
            field=models.BooleanField(blank=True, help_text='Do you own or have extensive knowledge of specialized mechanic tools? (Optional)', null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='sasp_leadership_experience',
            field=models.TextField(blank=True, help_text='Describe any relevant leadership experience (Optional).', null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='sasp_scenario_response',
            field=models.TextField(blank=True, help_text='Describe how you would handle a specific scenario (e.g., a high-speed pursuit ending in a crash).', null=True),
        ),
    ]
