# Generated by Django 4.1.13 on 2025-04-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobapplication_ems_medical_certification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='feedback',
            field=models.TextField(blank=True, help_text='Feedback provided by the reviewer.', null=True),
        ),
    ]
