# Generated by Django 5.2 on 2025-04-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobapplication_basic_pd_rules_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='basic_pd_rules',
            new_name='pd_rules_evidence',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='pd_rules_miranda',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='pd_rules_officer_down',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='pd_rules_radio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='pd_rules_scene_management',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='pd_rules_traffic_stops',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='pd_rules_use_of_force',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='pd_rules_vehicle_pursuit',
            field=models.TextField(blank=True, null=True),
        ),
    ]
