# Generated by Django 5.2 on 2025-04-06 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobapplication_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='reviewed_at',
            new_name='form_reviewed_at',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='reviewer',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='form_feedback',
            field=models.TextField(blank=True, help_text='Feedback provided during form review.', null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='form_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_job_forms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='interview_feedback',
            field=models.TextField(blank=True, help_text='Feedback provided during/after interview.', null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='interview_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='interview_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviewed_job_applicants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Form Review'), ('INTERVIEW_PENDING', 'Pending Interview'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected (Form Stage)'), ('REJECTED_INTERVIEW', 'Rejected (Interview Stage)')], default='PENDING', max_length=20),
        ),
    ]
