# Generated by Django 5.2 on 2025-04-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_rename_basic_pd_rules_jobapplication_pd_rules_evidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='ems_helped_someone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='ems_interest',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='ems_qualities',
            field=models.TextField(blank=True, null=True),
        ),
    ]
