# Generated by Django 5.2 on 2025-04-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobapplication_ems_helped_someone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='mechanic_interest',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='mechanic_problem_solving',
            field=models.TextField(blank=True, null=True),
        ),
    ]
