# Generated by Django 5.2 on 2025-04-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keybind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the keybind action', max_length=100, verbose_name='Name')),
                ('description', models.TextField(help_text='Description of what this keybind does', verbose_name='Description')),
                ('key', models.CharField(help_text='The key to bind (e.g., F1, E, etc.)', max_length=50, verbose_name='Key')),
                ('command', models.CharField(help_text='The command to execute when key is pressed', max_length=255, verbose_name='Command')),
                ('category', models.CharField(help_text='Category of the keybind (e.g., General, Vehicle, etc.)', max_length=50, verbose_name='Category')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this keybind is currently active', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Keybind',
                'verbose_name_plural': 'Keybinds',
                'ordering': ['category', 'name'],
            },
        ),
    ]
