# Generated by Django 5.2 on 2025-05-07 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_department_departmentchief_employee_calllog_rank_and_more'),
    ]

    operations = [
        # First delete all models
        migrations.DeleteModel(
            name='CallLog',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='DepartmentChief',
        ),
        migrations.DeleteModel(
            name='Rank',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Shift',
        ),
    ]
