# Generated by Django 5.2 on 2025-04-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_review_ems',
            field=models.BooleanField(default=False, verbose_name='Can Review EMS Apps'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_review_mechanic',
            field=models.BooleanField(default=False, verbose_name='Can Review Mechanic Apps'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_review_sasp',
            field=models.BooleanField(default=False, verbose_name='Can Review SASP Apps'),
        ),
    ]
