# Generated by Django 5.2 on 2025-04-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidebookentry',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='guidebook/thumbnails/'),
        ),
    ]
